### ISSUE TITLE
Why is Scotch Box landing page intercepting mydomain.com/index.html? 

### ISSUE THREAD

**Issue by ProbonoBonobo** [scotch-io/scotch-box#193] opened 2016-03-01 07:47 UTC
I use ScotchBox on my local machine, and I love it. Last month, I attempted to install it on my DigitalOcean cloudserver. It was a frustrating experience. I had no reason until yesterday to believe the installation attempt was even successful. I gathered from the unresolved support tickets I found that DigitalOcean's virtualization firmware might not even be compatible with Vagrant's. No biggie. I just configured Apache server to serve without virtualization. Until yesterday, my Apache server showed '<a href="http://www.kevinzeidler.com/index.html">index.html</a>' at mydomain.com as usual. It worked. It was great. Suddenly, as of this writing, '[my website](http://www.kevinzeidler.com) is being intercepted by the Scotch Box landing page. I have no idea what to make of this issue. I have attempted to delete all traces of Vagrant from my machine, but after removing the files at my server's root, I'm getting errors like these when I try to use Vagrant's own methods:

root@kevinzeidler:~# vagrant destroy
==> default: VM not created. Moving on...
root@kevinzeidler:~# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /root/base

Any idea why this might be happening? And how I might get rid of Vagrant/Scotch Box once and for all?

**Comment by ProbonoBonobo** [comment] 2016-03-01 07:52
I should just clarify, since it's not clear from reading the error description without following the links: explicitly going to [mydomain.com/index.html](http://www.kevinzeidler.com/index.html) works fine; it's specifically the hostname mydomain.com that shows the Scotch Box landing page, saying that my Ubuntu 14.04 sever is up and running, etc.  The unit tests all pass, with one exception: interestingly, mySQL is not connected for some reason. I wonder if that might have something to do with it? (I'm not using SQL at all on my site.)

**Comment by ncerminara** [comment] 2016-03-01 16:14
There's not really a solid way to provision "scotch/box" on DO. Digital Ocean does provide their own box though.

**Comment by joepurdy** [comment] 2016-03-01 16:34
Sounds like the document root for the apache server on your DO server is serving the scotch box index.php file. Even if you destroy the vagrant instance the files can still exist somewhere and Apache will serve index.php over index.html when the root domain is requested.

Can you SSH to your server, navigate to your document root and list the contents to verify there isn't a conflict between schotch box's index.php and your index.html?

**Comment by joepurdy** [comment] 2016-03-01 16:43
@ProbonoBonobo I checked your repo for your site and can see where you committed the scotch/box index.php file a couple days ago. This is the cause of the problem with your site and I've submitted a PR to correct it.

cc: @ncerminara Not an issue with scotch/box, plz close

**Comment by ProbonoBonobo** [comment] 2016-03-01 17:59
This was indeed the cause of the issue. Thanks to you both!

**Closed** 2016-03-17 15:37 UTC
