### ISSUE TITLE
npm install not working when installing laravel/elixir

### ISSUE THREAD

**Issue by iamgoodbytes** [scotch-io/scotch-box#126] opened 2015-10-19 08:26 UTC
I'm trying to install elixir on scotchbox via npm install, but I'm getting a number of errors. After reading on the web, other people seem to mention that this might be a permissions problem. Running npm install with sudo gives the same results: 

vagrant@scotchbox:/var/www$ sudo npm install
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"2.13.0"})
npm WARN deprecated vue-component-compiler@1.1.12: vue-component-compiler has been merged into vueify.
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"2.13.0"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"2.13.0"})
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"2.13.0"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"2.13.0"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"2.13.0"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"2.13.0"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"2.13.0"})

What's weird is that I can install elixir just fine on my host system (mac) running node v.0.10.26. Any idea what can be wrong here or if this is scotchbox related at all?

**Comment by caiokawasaki** [comment] 2015-10-22 14:28
Same problem here, I think the problem is vue-component-compile, npm say's it's deprecated and has been merged into vueify... May another package is still looking for vue-component-compile...

**Comment by ncerminara** [comment] 2015-10-22 14:34
Try updating Node first?

**Comment by ncerminara** [comment] 2015-11-03 19:09
Node was updated in 2.5: https://scotch.io/bar-talk/announcing-scotch-box-2-5#node-js-updates

**Closed by ncerminara** 2015-11-03 19:09 UTC
