### ISSUE TITLE
Vagrant was unable to mount VirtualBox shared folders

### ISSUE THREAD

**Issue by mohsinkabir** [scotch-io/scotch-box#296] opened 2017-03-16 09:51 UTC
I am facing an issue : 
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 var_www /var/www

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such file or directory

How can i solve it.

**Comment by Wombatpm** [comment] 2017-03-23 15:37
I just ran into this recently after some updates.  The solution I found was 
```
vagrant plugin install vagrant-vbguest
vagrant vbguest
```
Then when I did `vagrant up` it ran through the process of installing the correct vbguest package into the box.

**Comment by terrafrost** [comment] 2017-03-30 14:59
Didn't work for me.

My Vagrantfile:

```
Vagrant.configure("2") do |config|
	config.vm.box = "scotch/box"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.hostname = "vagrant"

	config.vm.synced_folder ".", "/root/shared", :mount_options => ["dmode=777", "fmode=666"]
end
```

I did `vagrant box update` before doing `vagrant up`. I'm running the latest version (2.5). Here's the output:

https://pastebin.com/eMYRHvt3

I did `vagrant plugin install vagrant-vbguest` and got this:

```
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vbguest (0.13.0)'!
```

I did `vagrant vbguest` (apparently the VM needs to be running for `vagrant vbguest` to run):

```
[default] GuestAdditions 5.1.16 running --- OK.
```

I then did `vagrant halt` and `vagrant up`. Same thing.

I tried `vagrant destory` and `vagrant up`. Same thing.

**Comment by Wombatpm** [comment] 2017-03-30 16:39
If it helps any.  I'm running VBox 5.1.18 r114002  and Vagrant 1.9.2  on windows 10.

**Comment by Danonk** [comment] 2017-05-02 10:27
I also had to install
```
vagrant plugin install vagrant-winnfsd
```

**Comment by terrafrost** [comment] 2017-05-05 15:25
It worked with 5.1.18 for me as well.

Per https://www.virtualbox.org/wiki/Changelog 5.1.18 fixed the following seemingly relevant issues:

- Shared Folders: fixed case insensitive filename access (5.1.16 regression; Windows guests only; bug #16549)
- Shared Folders: fixed access to long pathes (5.1.16 regression; Windows guests only; bugs #14651, #16564)

**Comment by whatnickcodes** [comment] 2017-05-15 16:45
Okay closing this!

**Closed by whatnickcodes** 2017-05-15 16:45 UTC

**Comment by mojili** [comment] 2017-09-27 06:44
I solved my problem with installing this plugin 
vagrant plugin install vagrant-vbguest

Thanks to @Wombatpm

**Comment by Dakemao** [comment] 2017-11-17 06:44
It worked for me. THXS @Wombatpm

**Comment by renatoadsumus** [comment] 2017-11-21 12:38
I solved my problem too installing this plugin!
vagrant plugin install vagrant-vbguest

**Comment by mynenisr** [comment] 2017-12-14 19:48
Glad that my problem solved. When I first used "vagrant plugin install vagrant-vbguest" Its the same problem, But when I did 
1. vagrant plugin install vagrant-winnfsd
2.  vagrant plugin install vagrant-vbguest
3. Vagrant up
Now it got resolved with no issues.
Thanks for taking time and posting it here.

**Comment by angelburov** [comment] 2018-02-02 07:56
@mynenisr I resolved my issue the exact same steps. Thanks a lot!

**Comment by agcrf5000** [comment] 2018-05-03 17:21
After running `vagrant up` for the first time, if you run into the error above, try doing a `vagrant reload`. This is worked for me. You do need the **vagrant-vbguest** plugin installed, so make sure you have the plugin installed before initially running `vagrant up`.

Two more things:
- don't change the settings in Vagrant file, except the IP if you have to. 
- You shouldn't have to run `vagrant vbguest`. Running `vagrant reload` should resolve the issue for you.

**Comment by alexandregv** [comment] 2018-07-05 23:35
If you still have problems with Shared Folders, open VirtualBox GUI, open your VM's settings and go in the Storage tab. If the paths are prefixed with a buggy "\\\\?\\", see https://github.com/hashicorp/vagrant/issues/9041#issuecomment-402301714

If it fixed the problem but now you get an error like `GuestAdditions versions on your host (5.2.14) and guest (5.1.34) do not match.`
see https://github.com/dotless-de/vagrant-vbguest/issues/300#issuecomment-402881079

**Comment by syoshida20** [comment] 2018-12-21 12:06
I solved the same issue, Thank you so much

**Comment by tpask** [comment] 2019-01-27 06:05
I ran "vagrant plugin install vagrant-vbguest; vagrant vbguest" a few months back to fix issues with not being able to mount shares.  That did the trick then.
However, the issue reappeared after a few months.  I'm not entirely sure why.
So,  I destroyed all my vagrant images (probably didn't need to do that but I didn't need them anyway), uninstalled the plugin (vagrant plugin uninstall vagrant-vbguest), and updated to the latest version of vagrant. 
The combination of uninstalling vagrant-vbguest and updating vagrant to the latest version fixed my issue.

**Comment by oliverpolden** [comment] 2019-02-07 16:38
The initial solution still worked for me today. My vagrant box was still running when I ran them.

**Comment by jimmy-yu-1990** [comment] 2019-03-21 03:37
Is the reason of the version of virtural box and vagrant?

**Comment by jimmy-yu-1990** [comment] 2019-03-21 03:38
i meet the error too ,help!

**Comment by mirageglobe** [comment] 2019-05-22 13:11
if you are on mac
```
brew cask install virtualbox
brew cask install virtualbox-extension-pack
```
the make sure you have the right plugins
```
vagrant plugin list
```
install the usual suspects (this plugin is the one that updates virtualbox guests) - check https://github.com/hashicorp/vagrant/wiki/Available-Vagrant-Plugins
```
vagrant plugin install vagrant-vbguest  
```
if you have issues, its probably in your vagrantfile. clean it up and retry.

**Comment by chathunpc** [comment] 2019-10-22 06:19
Make sure disable or allow your firewall and antivirus software to allow network transaction I spent many hours to get this :)

**Comment by nyanmyohtet-scm** [comment] 2019-12-13 04:13
> I just ran into this recently after some updates. The solution I found was
> 
> ```
> vagrant plugin install vagrant-vbguest
> vagrant vbguest
> ```
> 
> Then when I did `vagrant up` it ran through the process of installing the correct vbguest package into the box.

It worked for me. Thank you so much @Wombatpm .

**Comment by arslanramay** [comment] 2020-02-01 21:07
> I just ran into this recently after some updates. The solution I found was
> 
> ```
> vagrant plugin install vagrant-vbguest
> vagrant vbguest
> ```
> 
> Then when I did `vagrant up` it ran through the process of installing the correct vbguest package into the box.

It worked for me. Thanks man!

**Comment by delife-7** [comment] 2020-03-20 19:35
i deleted vergant on virtual box then i installed this plugin:
vagrant plugin installs vagrant-vbguest vagrant vbguest
this worked for me

**Comment by n-orgx** [comment] 2020-04-07 21:21
It works after installing the plugin. Here is my vagrantfile 
```
$script = <<SCRIPT
apt-get update
apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io
groupadd docker
usermod -aG docker vagrant
curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/loc>chmod +x /usr/local/bin/docker-compose
apt-get install -y default-jdk maven
SCRIPT
```

Vagrant.configure(2) do |config|
  config.vm.provision "shell", inline: $script
  config.vm.box = 'debian/stretch64'
  config.vm.synced_folder ".", "/home/vagrant/01-JAVA",type:"virtualbox"
end

**Comment by penglian518** [comment] 2020-04-11 21:25
For Ubuntu as guest box, an additional step to delete the /vagrant folder and the soft link file "vagrant" in my box is required. 

> I just ran into this recently after some updates. The solution I found was
> 
> ```
> vagrant plugin install vagrant-vbguest
> vagrant vbguest
> ```
> 
> Then when I did `vagrant up` it ran through the process of installing the correct vbguest package into the box.

**Comment by sadalsuud** [comment] 2021-10-23 01:12
with 

vagrant plugin install vagrant-vbguest

work on xubuntu 21.10
